AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS backend for Bloodrush

Globals:
  Function:
    Timeout: 300

Resources:
  ################
  #    Cognito   #
  ################

  CognitoPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: 'Bloodrush'

  ################
  #   DynamoDB   #
  ################

  TeamsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: round
          AttributeType: N
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: round
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  #################
  #    AppSync    #
  #################

  BloodrushQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: 'BloodrushQLApi'
      AuthenticationType: API_KEY

  BloodrushQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt BloodrushQLApi.ApiId
      Definition: |
        schema {
          query: Query
        }
        type Team {
          id: ID!
          name: String
        }
        type Game {
          round: Int!
          date: AWSDateTime!
        }
        type Query {
          getTeams: [Team]!
          getGames: [Game]!
        }

  ###########################
  #    AppSync Resolvers    #
  ###########################

  GetTeamsResolver:
    DependsOn: BloodrushQLSchema
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt BloodrushQLApi.ApiId
      TypeName: 'Query'
      FieldName: 'getTeams'
      DataSourceName: !GetAtt TeamsTableDataSource.Name
      RequestMappingTemplate: |
        {
            "version": "2017-02-28",
            "operation": "Scan"
        }
      ResponseMappingTemplate: |
        {
            "id": "${ctx.result.id}",
            "name": "${ctx.result.name}",
        }

  GetGamesResolver:
    DependsOn: BloodrushQLSchema
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt BloodrushQLApi.ApiId
      TypeName: 'Query'
      FieldName: 'getGames'
      DataSourceName: !GetAtt GamesTableDataSource.Name
      RequestMappingTemplate: |
        {
            "version": "2017-02-28",
            "operation": "Scan"
        }
      ResponseMappingTemplate: |
        {
            "round": "${ctx.result.round}",
            "date": "${ctx.result.date}",
        }

  #############################
  #    AppSync Datasources    #
  #############################

  TeamsTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt BloodrushQLApi.ApiId
      Name: 'TeamsTableDataSource'
      Type: 'AMAZON_DYNAMODB'
      DynamoDBConfig:
        TableName: !GetAtt TeamsTable.Arn
        AwsRegion: !Ref AWS::Region
      ServiceRoleArn: !GetAtt ServiceRole.Arn

  GamesTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt BloodrushQLApi.ApiId
      Name: 'GamesTableDataSource'
      Type: 'AMAZON_DYNAMODB'
      DynamoDBConfig:
        TableName: !GetAtt GamesTable.Arn
        AwsRegion: !Ref AWS::Region
      ServiceRoleArn: !GetAtt ServiceRole.Arn

  LocalDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt BloodrushQLApi.ApiId
      Name: 'LocalDataSource'
      Description: 'Local AppSync datasource'
      Type: 'NONE'
      ServiceRoleArn: !GetAtt ServiceRole.Arn

  ##############################
  #    IAM Roles & Policies    #
  ##############################

  ServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'appsync.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'

  ##########################
  #    Template Outputs    #
  ##########################

Outputs:
  GraphQLApi:
    Description: GraphQL endpoint
    Value: !GetAtt BloodrushQLApi.GraphQLUrl
